export const CONTROLLER_PREFIX = {
  AUTH: 'auth',
  USER: 'users',
  PROTECTED: 'protected',
  ACCOUNT: 'accounts',
  CITIZEN: 'citizens',
  HOUSEHOLD: 'households',
  MEMBER: 'members',
  FEE: 'fees',
  PAYMENT: 'payments',
} as const

export const AUTH_ENDPOINT = {
  '/health': ['GET'],
  '/check-mail': ['GET'],
  '/citizens': ['POST', 'DELETE', 'GET'],
  '/citizens/:id': ['PATCH', 'DELETE', 'GET'],
  '/households': ['POST', 'DELETE', 'GET'],
  '/households/:id': ['PATCH', 'DELETE', 'GET'],
  '/accounts': ['POST', 'DELETE', 'GET'],
  '/accounts/:id': ['PATCH', 'DELETE', 'GET'],
  '/accounts/:id/role': ['PATCH'],
  '/accounts/:id/restore': ['PATCH'],
  '/auth/login': ['POST'],
  '/auth/register': ['POST'],
  '/auth/refresh-token': ['POST'],
  '/auth/logout': ['POST'],
  '/auth/reset-password': ['POST'],
  '/auth/otp': ['POST'],
  '/auth/verify-otp': ['POST'],
  '/protected/profile': ['GET', 'POST'],
  '/protected/password': ['POST'],
  '/protected/soft-delete': ['DELETE'],
  '/protected/refresh-tokens/:tokenId': ['DELETE'],
  '/protected/logout-all-devices': ['POST'],
  '/fees': ['POST', 'DELETE', 'GET'],
  '/fees/:id': ['PATCH', 'DELETE', 'GET'],
  '/members': ['POST', 'DELETE', 'GET'],
  '/members/:id': ['PATCH', 'DELETE', 'GET'],
  '/members/household/:householdId/change-head': ['POST'],
  '/members/household/:householdId/change-history': ['GET'],
  '/members/household/:householdId/split-household': ['POST'],
  '/payments': ['POST', 'GET', 'DELETE'],
  '/payments/:id': ['PATCH', 'GET', 'DELETE'],
  '/analytics/count': ['GET'],
  '/analytics/count-gender': ['GET'],
  '/analytics/count-fee-payment-by-date': ['GET'],
  '/analytics/count-fee-payment': ['GET'],
}
